language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: XPIKS_BINARY=binary
      
git:
  depth: 3

addons:
  sonarcloud:
    organization: "ribtoks-github"
    token:
      secure: "jlW0NkIDzrxD+elZgVR0nK01hNU4KEDd08EiH3hLwtDCB2rlzJC2alJCNqjQT+EDtwbUH2h62KJbAMxBP8apWaVcxkCtF6r2rporaJKxaFpXCjhMZSGZoa+GIsl4avMQPkPXBYGSPMZV521glxE7QVTjd1ExF5gon8H3RS8zaq9u97V5RgQPfsjmRrlP3etqdGbxjyvH2OQCQhncd6voMTEtZApVAGhdtaFrBhxwMFGP3SXivAxI7sGqeXPRam/IeHGsofOyt5WqYjkGYrube8plf94qt7/2F7nuvjjmKuXjS/INTUpd+eCJ+xWBynNRwfmqxqqst3PILNLkvh7Y5L7FYx92VmRyWA2xZnXkranb5OYjQyjAplDpiKCFjbJ5IiWf+4ohwiwm0kPIxl0Jx0NjMJkiqsdVXpHQANRbLsnU5YO6zijCp7F17QFJtmjqMihvfOqjYjhX57b2QuTg8QFiFqH5foCvqw4xNgjb/5yY1Yy7ANJsbbGnISLUsCcb18eVqQGda7m6xCX7gktDJoQYqIJqk/KYbPPgxZNkifeHijLn1MI40wyRcFUI/wdJHBkuaOIhHZclsxhKPjapZM9etIYvwdnsEYnXUlmxhV/nPp8wPJNcDcDJ41ycEeH3Hr0kw9qQbxbWKGV2bhJEQgCDPZFtEnServQXcLPfaFU="
    branches:
      - sonarqube
    
cache:
  apt: true
  directories:
    - my-apt-cache
    - '$HOME/.sonar/cache'

install:
  - ./scripts/ci/install-${TRAVIS_OS_NAME}.sh
  - . ./scripts/ci/env-${TRAVIS_OS_NAME}.sh

before_script:
  - ulimit -c unlimited -S       # enable core dumps

script:
  - $TRAVIS_BUILD_DIR/scripts/build/build_vendors_linux.sh travis-ci
  - ls -la libs/*
  - cd src/xpiks-qt/
  - qmake "CONFIG+= debug travis-ci without-video" xpiks-qt.pro
  - build-wrapper-linux-x86-64 --out-dir bw-output make
  - sonar-scanner
