language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: XPIKS_BINARY=binary
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: CORE_TESTS=tests QT_FATAL_WARNINGS=1
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: INTEGRATION_TESTS=tests QT_FATAL_WARNINGS=1
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: UI_TESTS=tests
    - os: osx
      compiler: clang
      env: XPIKS_BINARY=binary
      osx_image: xcode9.4
      if: branch = master
    - os: osx
      compiler: clang
      env: CORE_TESTS=tests QT_FATAL_WARNINGS=1
      osx_image: xcode9.4
      if: branch = master
    - os: osx
      compiler: clang
      env: INTEGRATION_TESTS=tests QT_FATAL_WARNINGS=1
      osx_image: xcode9.4
      if: branch = master
    - os: osx
      compiler: clang
      env: UI_TESTS=tests
      osx_image: xcode9.4
      if: branch = master
      
git:
  depth: 3
  quiet: true

cache:
  apt: true
  directories:
    - my-apt-cache

install:
  - ./scripts/ci/install-${TRAVIS_OS_NAME}.sh
  - . ./scripts/ci/env-${TRAVIS_OS_NAME}.sh

before_script:
  - ulimit -c unlimited -S       # enable core dumps
  - git fetch origin gh-pages
  - git checkout FETCH_HEAD -- api

script:
  - ${TRAVIS_BUILD_DIR}/scripts/build/build_vendors_${TRAVIS_OS_NAME}.sh travis-ci
  - ls -la libs/*
  - if [ -n "$XPIKS_BINARY" ]; then "$TRAVIS_BUILD_DIR/scripts/ci/travis-ci-xpiks-${TRAVIS_OS_NAME}.sh"; fi
  - if [ -n "$CORE_TESTS" ]; then "$TRAVIS_BUILD_DIR/scripts/ci/travis-ci-core-tests-${TRAVIS_OS_NAME}.sh"; fi
  - if [ -n "$INTEGRATION_TESTS" ]; then "$TRAVIS_BUILD_DIR/scripts/ci/travis-ci-integration-tests-${TRAVIS_OS_NAME}.sh"; fi
  - if [ -n "$UI_TESTS" ]; then "$TRAVIS_BUILD_DIR/scripts/ci/travis-ci-ui-tests-${TRAVIS_OS_NAME}.sh"; fi

