language: cpp

services:
  - docker

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: RUN_TEST=xpiks
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: RUN_TEST=core-tests QT_FATAL_WARNINGS=1
      if: branch != nightly
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: RUN_TEST=integration-tests QT_FATAL_WARNINGS=1
      if: branch != nightly
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: RUN_TEST=ui-tests
      if: branch != nightly
    - os: osx
      compiler: clang
      env: RUN_TEST=xpiks
      osx_image: xcode9.4
      if: branch = master OR branch = nightly
    - os: osx
      compiler: clang
      env: RUN_TEST=core-tests QT_FATAL_WARNINGS=1
      osx_image: xcode9.4
      if: branch = master
    - os: osx
      compiler: clang
      env: RUN_TEST=integration-tests QT_FATAL_WARNINGS=1
      osx_image: xcode9.4
      if: branch = master
    - os: osx
      compiler: clang
      env: RUN_TEST=ui-tests
      osx_image: xcode9.4
      if: branch = master

git:
  depth: 3
  quiet: true

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/.my-apt-cache
    - $HOME/.ccache

install:
  - ./scripts/ci/install-${TRAVIS_OS_NAME}.sh
  - . ./scripts/ci/env-${TRAVIS_OS_NAME}.sh

before_script:
  - ulimit -c unlimited -S       # enable core dumps
  - git fetch origin gh-pages
  - git checkout FETCH_HEAD -- api

script:
  - ${TRAVIS_BUILD_DIR}/scripts/build/build_vendors_${TRAVIS_OS_NAME}.sh travis-ci
  - ${TRAVIS_BUILD_DIR}/scripts/ci/travis-ci-${RUN_TEST}-${TRAVIS_OS_NAME}.sh

before_deploy:
  - ${TRAVIS_BUILD_DIR}/scripts/ci/travis-ci-deploy-${TRAVIS_OS_NAME}.sh

deploy:
  provider: releases
  api_key:
    secure: 2EMqL5NA8LR3fmggUbdxE3hwi2Ko8gDGoBjjVlpGxkOiaO3JumdPuy38sl2vs800x1cnGll54B9+ydXDTbBbMex8Y2j1V6h79ngCoCP1KfOpEwBhKmZchQlzGldvDrXEf5azX1HW7Q6jvRUlgiHH2XB/aSk79x4tY/QWqvHuZAAb0P8GBwTshDzqRL6LAYecakAp6aLHiZu1foVf7KkYQ96giKQ/BnDG2OwjMr5JxVjMCUnsf6yECcdWdD/3oJ1usSJLnWJSLDkNwwuw0Z12jltgOeoRRxcB/k0E/XBMLTw/rxYt8hxKrIWSeEAvrVhfkhjPoAW9S9/kz8SPf5hbNiVBkNjSglDXP9X9sJe0kT8v6aT5QHgYsb0MKPsF0kZs5dGSXMDfOMTakIHzDAKRFgjI9/a49saXM7eaMrzIynmaIwV1XU++lN1Kz+GptFr3+reYeJg1mRKaPj/duTfL9kVats0yH9O1oeCrDSkedIasoSGWrONP5ifRJ9mWbXHtik4gNYeoF17lmKju36G08yXLP36vd81b7NyGNebFu1s/4s2Mix/gG1vOObVAZQSGzgZWL/XUlHZEA9qRge8/B8w1wdqcuV1lZy/3mtzCa/QZDTlNCnP5PvCs4qMRLz9bYlaRWuOdZVDoWZon9gLaiLrQYcVmieIDfEODuNZxAWo=
  file_glob: true
  file: Xpiks-Nightly.dmg
  draft: true
  skip_cleanup: true
  prerelease: true
  name: Nightly
  overwrite: true
  on:
    branch: nightly
    condition: $RUN_TEST = xpiks
