language: cpp

services:
  - docker

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: RUN_TEST=xpiks
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: RUN_TEST=core-tests QT_FATAL_WARNINGS=1
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: RUN_TEST=integration-tests QT_FATAL_WARNINGS=1
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: RUN_TEST=ui-tests
    - os: osx
      compiler: clang
      env: RUN_TEST=xpiks
      osx_image: xcode9.4
      if: branch = master
    - os: osx
      compiler: clang
      env: RUN_TEST=core-tests QT_FATAL_WARNINGS=1
      osx_image: xcode9.4
      if: branch = master
    - os: osx
      compiler: clang
      env: RUN_TEST=integration-tests QT_FATAL_WARNINGS=1
      osx_image: xcode9.4
      if: branch = master
    - os: osx
      compiler: clang
      env: RUN_TEST=ui-tests
      osx_image: xcode9.4
      if: branch = master
      
git:
  depth: 3
  quiet: true

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/.my-apt-cache
    - $HOME/.ccache

install:
  - ./scripts/ci/install-${TRAVIS_OS_NAME}.sh
  - . ./scripts/ci/env-${TRAVIS_OS_NAME}.sh

before_script:
  - ulimit -c unlimited -S       # enable core dumps
  - git fetch origin gh-pages
  - git checkout FETCH_HEAD -- api

script:
  - ${TRAVIS_BUILD_DIR}/scripts/build/build_vendors_${TRAVIS_OS_NAME}.sh travis-ci
  - ls -la libs/*
  - ${TRAVIS_BUILD_DIR}/scripts/ci/travis-ci-${RUN_TEST}-${TRAVIS_OS_NAME}.sh"; fi

after_failure:
  - cat /tmp/vsftpd.log
