language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: XPIKS_BINARY=binary
    - os: linux
      dist: trusty
      sudo: required
      env: CORE_TESTS=tests QT_FATAL_WARNINGS=1
    - os: linux
      dist: trusty
      sudo: required
      env: INTEGRATION_TESTS=tests QT_FATAL_WARNINGS=1
    - os: linux
      dist: trusty
      sudo: required
      env: UI_TESTS=tests
      
git:
  depth: 3


env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "GK9b2y7xTZgBhTtziCaQTBwjVh72KdaoVqaez5kNeKPUQUm7nEt2NsaIPQyMi2oe6hwOXV1cgTag08udDU5sJoPtj3PhqxkuRwY4QqNSvBQObgKr+Jaad66ZioOOsrVh3OuLI+8Zt75MYSyX+NdiyTApUSbcZIdU5BIsq9R70TAWrZiT/QlcdYVt7iB4DTHFvPDY/Eh8Y0JY+0UFSXIRAAEnjk/KuHSoYjPbCQ1HLG/LDqtibIsUWH4+njjT5NvMFcI5nOSgPZuQ3D7pXizMx6uDzbq5fUx4boh3bLBFbFLXTH/+vPpFaqj1dGAQ3X2RL5SyydWAmVfQJ8exSXNcNEbujbiZg6Ob0OqgiK2IM9kPuMh7TOsDdwEZcnZYhkivL4WsoVbnld54mw8kAZLotiC+k52eLlmNDP+PUVK0d4ZCMA8cwVmpuHixSQevp1zxCofT/hE2Wgwez3IKWnmxiZmomYOiexOxYP6FkxHOR/YRLZGmtN+Sn/X88GRiaYt8zi5UXH7o3f2fFIeavcIF70t0hOCYRbALLm+KUuu3+VWLUQ+4FEE12cATbdTOUc+5UR9JJyZQrqOBDvIF3eN2EuYieF9+S6CoDaKaAXhseoYMYflxKF8pg1G7snwYMTRnkLuxHK8dCUXAlKaQnSwU2ZEA2avlxQnjbSDm1F3zASg="
  coverity_scan:
    project:
      name: "Xpiks-qt"
      version: "1.5"
      description: "Build submitted via Travis CI"
    branch_pattern: coverity_scan
    notification_email: kushnirtv@gmail.com
    build_command: make
cache:
  apt: true
  directories:
    - my-apt-cache

install:
  - ./scripts/ci/install-${TRAVIS_OS_NAME}.sh
  - . ./scripts/ci/env-${TRAVIS_OS_NAME}.sh

before_script:
  - ulimit -c unlimited -S       # enable core dumps
  - ${TRAVIS_BUILD_DIR}/scripts/build/build_vendors_linux.sh travis-ci
  - ls -la libs/*
  - if [ -n "$XPIKS_BINARY" ]; then "$TRAVIS_BUILD_DIR/scripts/ci/travis-ci-xpiks.sh"; fi
  - if [ -n "$CORE_TESTS" ]; then "$TRAVIS_BUILD_DIR/scripts/ci/travis-ci-core-tests.sh"; fi
  - if [ -n "$XPIKS_BINARY" ]; then cd xpiks-qt/; fi
  - if [ -n "$XPIKS_BINARY" ]; then qmake "CONFIG+= debug travis-ci without-video" xpiks-qt.pro; fi

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi
